config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # devise_for :installs
  get 'settings/index'
  resources :employees
  resources :jobs, only: [:new, :create, :destroy]
  resources :searches
  get 'jobs/settings'
  root to:"employees#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/employee.rb
class Employee < ApplicationRecord

    
    belongs_to :job
    validates :name, presence: {message: " é obrigatório" }
    validates :email, presence: {message: " é obrigatório" } , uniqueness: {message: "O email %{value} já está cadastrado"}
    validates :salary, :job_id, presence: true
    # validates :name, uniqueness: true

    def self.search(search)
        if search
            where(["name LIKE ?", "%#{search}%"])
        else
            all
        end
    end
end

app/models/install.rb
class Install < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/job.rb
class Job < ApplicationRecord
    has_many :employees
    validates :name, uniqueness: true
end

app/models/search.rb
class Search < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_user!
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  before_action :set_employee, only: [:show, :edit, :update, :destroy]

  def index
    #@employees = Employee.all
    @q = Employee.ransack(params[:q])
    @employees = @q.result(distinct: true)
    # @employees = Employee.search(params[:search])
  end

  def new
    @employee = Employee.new
  end

  def create
    @employee = Employee.create(employee_params)

    if @employee.valid?
      SlackNotifier::CLIENT.ping "#{@employee.name} é a(o) nova(o) funcionária(o)"
      redirect_to employees_path
    else
      flash[:errors] = @employee.errors.full_messages
      redirect_to new_employee_path
    end

  end

  def show
   
  end

  def edit
    
  end

  def update
    @employee.update(employee_params)
    redirect_to employees_path
  end


  def destroy
    @employee.destroy
    SlackNotifier::CLIENT.ping "#{@employee.name} não é mais funcionária(o)"
    redirect_to employees_path
  end

  private
    def set_employee
      @employee = Employee.find(params[:id])
    end

    def employee_params
      params.require(:employee).permit(:name, :email, :salary, :job_id)
    end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  def index
    @jobs = Job.all
  end

  def new
    @job = Job.new
  end

  def settings
    @job = Job.new
  end

  def create
    @job = Job.create(params.require(:job).permit(:name))

    if @job.valid?
      redirect_to employees_path
    else
      flash[:errors] = @job.errors.full_messages
      redirect_to new_job_path
    end
  end

  def destroy
    @job = Job.find(params[:id])
    @job.destroy
    redirect_to job_path
  end
end

app/controllers/settings_controller.rb
class SettingsController < ApplicationController
  def index
    @jobs = Job.all
  end

  def create
    @job = Job.create(params.require(:job).permit(:name))

    if @job.valid?
      redirect_to employees_path
    else
      flash[:errors] = @job.errors.full_messages
      redirect_to new_job_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/settings_helper.rb
module SettingsHelper
end

app/views/employees/_employee_list.html.erb
    <table class="table">
        <thead>
            <tr>
                <th><%= sort_link(@q, :name, 'Nome') %></th>
                <th>E-mail</th>
                <th>Cargo</th>
                <th>Salário</th>
                <th>Ações</th>
            </tr>
        </thead>
        <tbody>
            <% @employees.each do |employee| %>
                <tr>
                    <td><%= link_to employee.name, employee_path(employee) %></td>
                    <td><%= employee.email %></td>
                    <td><%= employee.job.name %></td>
                    <td>R$ <%= employee.salary %></td>
                    <td class="action-btns"><%= button_to "Editar", edit_employee_path(employee.id), method: :get, :class=> 'btn btn-gray btn-small gray-font round-corner' %> <%= button_to "Deletar", employee_path(employee.id), method: :delete, :class=> 'btn btn-gray btn-small red-font round-corner' %></td>
                </tr>
            <% end %>
        </tbody>
    </table>

app/views/employees/create.html.erb
<h1>Employees#create</h1>
<p>Find me in app/views/employees/create.html.erb</p>

app/views/employees/destroy.html.erb
<h1>Employees#destroy</h1>
<p>Find me in app/views/employees/destroy.html.erb</p>

app/views/employees/edit.html.erb
<div class="jumbotron">
  <h1> Editar Funcionário </h1>
  <%= link_to "Voltar página", '/', :class=> 'btn btn-gray btn-big purple-font' %>
</div>

<div class="errors">
    <% if flash[:errors] %>
        <% flash[:errors].each do |error| %>
            <p style="color: red"><%= error%></p>
        <%end%>
    <%end%>
</div>


<div class="container">
    <%= form_for @employee, :html=> {:class=> 'employee-form'} do |f|%>
        <%= f.label :name %>
        <%= f.text_field :name %>
        <%= f.label :email %>
        <%= f.text_field :email %>
        <%= f.label :job %>
        <%= f.select :job_id, Job.all.collect {|u| [u.name, u.id]} %>
        <%= f.label :salary %>
        <%= f.number_field :salary %>

        <%= f.submit 'Salvar alterações', :class=> 'btn btn-purple'%>
    <%end%>
</div>

app/views/employees/index.html.erb
<div class="jumbotron">
  <h1> Quadro de Funcionários </h1>
  <%= button_to "Novo Funcionário", new_employee_path, method: :get, :class=> 'btn btn-big btn-purple' %>
</div>


<div class="container">
  <div class="search">
    <%= search_form_for @q, remote: true do |f| %>
      <%= f.label :name_cont, 'Nome', :class=> 'hidden'%>
      <%= f.search_field :name_cont, placeholder: 'Digite sua busca', :class=> 'search-input ' %>
      <%= f.submit 'Buscar', :class=> 'btn btn-big btn-purple' %>
    <% end %>
  </div>

  <div class="employee-list">
    <%= render "employee_list" %>
  </div>
</div>

app/views/employees/new.html.erb
<div class="jumbotron">
  <h1> Novo Funcionário </h1>
  <%= link_to "Voltar página", '/', :class=> 'btn btn-big btn-gray purple-font' %>
</div>

<div class="errors">
    <% if flash[:errors] %>
        <% flash[:errors].each do |error| %>
            <p style="color: red"><%= error%></p>
        <%end%>
    <%end%>
</div>

<div class="container">
    <%= form_for @employee, :html=> {:class=> 'employee-form'} do |f|  %>
    <%= f.label :name, 'Nome' %>
    <%= f.text_field :name %>
    <%= f.label :email %>
    <%= f.text_field :email %>
    <%= f.label :job_id, 'Cargo' %>
    <%= f.select :job_id, Job.all.collect {|u| [u.name, u.id]} %>
    <%= f.label :salary, 'Salário' %>
    <%= f.number_field :salary %>

    <%= f.submit 'Cadastrar Funcionário', :class=> 'btn btn-purple' %>
    <%end%>
</div>

app/views/employees/show.html.erb
<div class="jumbotron">
  <h1> Informações do Funcionário </h1>
  <%= link_to "Voltar página", '/', :class=> 'btn btn-gray btn-big purple-font' %>
</div>

<div class="container">
    <div class="employee-form employee-show">
            <h2><%= @employee.name %> </h2>
            <p class="gray-font"><%= @employee.job.name %> </p>
            <p><%= @employee.email %> </p>
            <p>R$ <%= @employee.salary %> </p>
            <%= button_to "Editar Funcionário", edit_employee_path, method: :get, :class=> 'btn btn-purple' %>
            <%= button_to "Deletar Funcionário", employee_path, method: :delete, :class=> 'btn btn-gray red-font'%>
    </div>
</div>

app/views/employees/update.html.erb
<h1>Employees#update</h1>
<p>Find me in app/views/employees/update.html.erb</p>

app/views/jobs/create.html.erb
<h1>Jobs#create</h1>
<p>Find me in app/views/jobs/create.html.erb</p>

app/views/jobs/destroy.html.erb
<h1>Jobs#destroy</h1>
<p>Find me in app/views/jobs/destroy.html.erb</p>

app/views/jobs/index.html.erb
<h1>Jobs#index</h1>
<p>Find me in app/views/jobs/index.html.erb</p>

app/views/jobs/new.html.erb
<h1>Jobs#new</h1>

<% if flash[:errors] %>
    <% flash[:errors].each do |error| %>
        <p style="color: red"><%= error%></p>
    <%end%>
<%end%>

<%= form_for @job do |f|%>
    <%= f.label :name %>
    <%= f.text_field :name %>

    <%= f.submit %>
<%end%>

app/views/jobs/settings.html.erb
<h1>Settings aqui</h1>


<% if flash[:errors] %>
    <% flash[:errors].each do |error| %>
        <p style="color: red"><%= error%></p>
    <%end%>
<%end%>

<%= form_for @job do |f|%>
    <%= f.label :name %>
    <%= f.text_field :name %>

    <%= f.submit %>
<%end%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Livimanager</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <header class="header">
      <div class="header-container">
        <div class="logo">
          <h1>Livimanager</h1>
        </div>
        <div class="header-nav">
          <% if user_signed_in? %>
            <%= link_to image_tag("user-icon.svg", :class=>'nav-img'), edit_user_registration_path, :class => 'navbar-link' %>
            <%= link_to image_tag("settings-icon.svg", :class=>'nav-img'), "/settings/index" %>
            <%= link_to image_tag("logout-icon.svg", :class=>'nav-img'), destroy_user_session_path, method: :delete %>
            
          <% end %>
        </div>
      </div>
    </header>
    
      <%= yield %>
  </body>
</html>

app/views/settings/index.html.erb
<div class="jumbotron">
  <h1> Configurações </h1>
  <%= link_to "Voltar página", '/', :class=> 'btn btn-gray btn-big purple-font' %>
</div>

<% if flash[:errors] %>
    <% flash[:errors].each do |error| %>
        <p style="color: red"><%= error%></p>
    <%end%>
<%end%>

<div class="container">
    <%= form_with(url: "/jobs", method: "post", class: "employee-form") do %>
        <h3>Cadastrar Cargo</h3>
        <%= label_tag(:name, "Nome") %>
        <%= text_field(:job, :name) %>

        <%= submit_tag("Cadastrar", class: 'btn btn-purple') %>
    <%end%>
</div>